### ISSUE TITLE
Plans for official integration into Mathjax

### ISSUE THREAD

**Issue by bergwald** [AmerMathSoc/mathjax-unicode-math#21]
Are there any plans to add this extension to the [list](https://docs.mathjax.org/en/latest/input/tex/extensions/index.html) of extensions officially integrated into Mathjax?

Being able to load `unicode-math` with the `\require` macro would allow it to be used in applications such as [diagrams.net](https://github.com/jgraph/drawio) that support Mathjax but don't directly allow access to its configuration.

**Comment by pkra** [comment]
This is a question you will need to ask the MathJax team. They can include this extensions if they want.

(I do suspect they will be hesitant to do so until MathJax v3 has additional font options because this extension uses a lot of unicode characters that the MathJax default fonts have no glyphs for.)

Closing as a question.
